name: to-do-build

on:
  push:
    branches: [ to-do ]
  pull_request:
    branches: [ to-do ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose -p to-do
